name: JMeter Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install JMeter
      run: |
        sudo apt-get update
        sudo apt-get install -y jmeter

    - name: Run JMeter Tests
      run: |
        jmeter -n -t jmeter/testplan.jmx -l jmeter/results.jtl

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-results
        path: jmeter/results.jtl

    - name: Check JMeter Logs
      run: |
        cat jmeter/results.jtl
